services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_NAME: "Dealer Reports"
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:mdyudgsTphh9Tug/LvWeApLuNuADrxAnDPsEzpa3A8w
      APP_URL: http://localhost:${APP_PORT:-8089}
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/storage/database.sqlite
      LOG_CHANNEL: stderr
    volumes:
      - app_storage:/var/www/storage
      - public_build:/var/www/public/build
    networks:
      - dealer-reports-net

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - "${APP_PORT:-8089}:80"
    volumes:
      - app_storage:/var/www/storage
      - public_build:/var/www/public/build
    depends_on:
      - app
    networks:
      - dealer-reports-net

volumes:
  app_storage:
    driver: local
  public_build:
    driver: local

networks:
  dealer-reports-net:
    driver: bridge
